### ISSUE TITLE
`send_and_wait` doesn't properly mock `aiokafka.send_and_wait`

### ISSUE THREAD

**Issue by gabysbrain** [alm0ra/mockafka-py#52]
**Describe the bug**

aiokafka's version of `send_and_wait` has 2 positional arguments (see https://aiokafka.readthedocs.io/en/stable/api.html#aiokafka.AIOKafkaProducer.send_and_wait). However, in `FakeAIOKafkaProducer` these arguments aren't there and the *args and **kwargs are not properly passed from `send_and_wait` to `_produce` and you get an exception when using this function:

`TypeError: FakeAIOKafkaProducer._produce() missing 1 required positional argument: 'topic'`

**To Reproduce**
```
producer = FakeAIOKafkaProducer()
producer.send_and_wait("topic_name", "sdfjhasdfhjsa", key="datakey")
```
:boom: 

**Expected behavior**
It should not throw an exception

**Screenshots**
```
/usr/local/lib/python3.12/site-packages/sentry_sdk/tracing_utils_py3.py:64: in func_with_tracing
    return func(*args, **kwargs)
src/kafka.py:90: in process
    asyncio.run(self.send_updated_records(plant_data.plant_key, updated_data))
/usr/local/lib/python3.12/asyncio/runners.py:194: in run
    return runner.run(main)
/usr/local/lib/python3.12/asyncio/runners.py:118: in run
    return self._loop.run_until_complete(task)
/usr/local/lib/python3.12/asyncio/base_events.py:685: in run_until_complete
    return future.result()
src/kafka.py:106: in send_updated_records
    await self.producer.send_and_wait(ct, serialized_record, key=plant_key)
/usr/local/lib/python3.12/site-packages/mockafka/aiokafka/aiokafka_producer.py:40: in send_and_wait
    await self.send()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <mockafka.aiokafka.aiokafka_producer.FakeAIOKafkaProducer object at 0x7f5302d6dd30>, args = ()
kwargs = {}

    async def send(self, *args, **kwargs):
>       await self._produce(**kwargs)
E       TypeError: FakeAIOKafkaProducer._produce() missing 1 required positional argument: 'topic'
```

**Desktop (please complete the following information):**
 - OS: linux
 - python version: 3.12
 - mockafka-py version: 0.1.52

**Comment by alm0ra** [comment]
hey @gabysbrain , 
thanks for reporting the issue .
can you fix it by opening a PR?

**Comment by alm0ra** [comment]
Dear @gabysbrain 

if fixed it in this [release](https://github.com/alm0ra/mockafka-py/releases/tag/v0.1.53)

**Comment by gabysbrain** [comment]
Thank you! Nice project btw :)
