### ISSUE TITLE
The messages are not cleared from topic once consumed. 

### ISSUE THREAD

**Issue by ssmails** [alm0ra/mockafka-py#61]
**Describe the bug**
Created a mock producer and consumer as shown in the snippet. When a unit test is run, code uses mock producer to produce multiple messages to 2 topics. Testcase checks if the produced messages are received, via polling the mock consumer.
When multiple messages are produced on > 1 topic, the behavior is inconsistent. 
- The messages are not cleared from topic once consumed. 
- All messages are not received on the expected topic.

Even with a single topic is used and only produce multiple messages on that topic-
- The messages are not cleared from topic once consumed. 

**To Reproduce**

- replace constants in files below. Run with TestCase to produce multiple messages on same topic, check consumed messages.
- replace constants in files below. Run with TestCase to produce multiple messages on different topic, check consumed messages.

previously consumed messages are still shown.

```
import json
import uuid
from random import randint

from mockafka import FakeProducer, setup_kafka, FakeAdminClientImpl
from mockafka.admin_client import NewTopic

class MockProducer:

    def __init__(self):
        admin = FakeAdminClientImpl()
        admin.create_topics([
            NewTopic(topic=KAFKA_TOPIC_AUDITS, num_partitions=2),
            NewTopic(topic=KAFKA_TOPIC_RAW_DOCS, num_partitions=2)
        ])
        self._producer = FakeProducer()

    def produce(self, topic: str, key: str, message: dict):
        try:
            logger.info(f'sent msg to {topic}, key: {key}, {json.dumps(message, indent=4)}')
            self._producer.produce(
                key=key + str(uuid.uuid4()),
                value=message,
                topic=topic,
                partition=randint(0, 1)
            )
        except Exception as e:
            logger.error(f"kafka produce error:{e} for topic:{topic}, key:{key}, message:{message}")
```

```
from typing import Any
from mockafka import FakeConsumer

class MockConsumer:
    def __init__(self):
        self._consumer = FakeConsumer()

    def consume(self, topics, msg_cnt=1) -> Any:
        self._consumer.subscribe(topics)
        messages = []
        cnt = 1
        while cnt <= msg_cnt:
            message = self._consumer.poll(timeout=1.0)
            print("mock consumer received:", message.value())
            if message is not None:
                messages.append(message.value())
                cnt = cnt + 1
            self._consumer.commit(message)

        # self._consumer.unsubscribe(topics)
        return messages

    def close(self):
        self._consumer.close()
```

**Expected behavior**
The messages should be removed from topic once consumed. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - python ver- 3.11
- lib version  mockafka-py==0.1.53

**Additional context**

**Comment by alm0ra** [comment]
Hey @ssmails ,
I don't have any idea how it could happen .
could you please provide a unit test?

**Comment by alm0ra** [comment]
@ssmails please look at this PR 

I think you forgot to add `clean=True` for your admin client 

in this test, I added parameterized test case that checks the number of produced messages with the number of consumed message

**Comment by ssmails** [comment]
@alm0ra thanks for looking into this. I copied the test sample you had and added a print msg as part of the test after the consumer runs, and am able to reproduce the issue I mentioned. 
I reduced the dataset to 4 runs as well, so its more clear.

In run 2 below, you see the 2 messages are the same. They should be different since a uuid is used as the msg produced per https://github.com/alm0ra/mockafka-py/pull/62/files#diff-6d0ff70a7ffbc6670cd1e7d92364fa4ad5c3e155734668e5f668aee512b59e8aR62

test_consumer_consistency.py::test_consumer_consistency[2] PASSED        [ 50%]
recv: {'u': '34635fbb-bdf3-44d3-baf0-e5fb4681fc53'}
recv: {'u': '34635fbb-bdf3-44d3-baf0-e5fb4681fc53'}

Similarly in test 3 and 4 below, we see that sometimes messages are duplicates, and sometimes unique.
If I run the test multiple times, everytime, the behaviour is different.

```
============================= test session starts ==============================
collecting ... collected 4 items

test_consumer_consistency.py::test_consumer_consistency[1] PASSED        [ 25%]
recv: {'u': '01d35b5b-b7da-4975-b91c-35f1d8bc8ff4'}

test_consumer_consistency.py::test_consumer_consistency[2] PASSED        [ 50%]
recv: {'u': '34635fbb-bdf3-44d3-baf0-e5fb4681fc53'}

recv: {'u': '34635fbb-bdf3-44d3-baf0-e5fb4681fc53'}

test_consumer_consistency.py::test_consumer_consistency[3] PASSED        [ 75%]
recv: {'u': '111f5a57-9815-4f16-b1d1-ab5e42af5fe9'}

recv: {'u': '111f5a57-9815-4f16-b1d1-ab5e42af5fe9'}

recv: {'u': 'd6b99d87-9636-4f76-a351-8c8b98abe45f'}

test_consumer_consistency.py::test_consumer_consistency[4] PASSED        [100%]
recv: {'u': 'db027dff-c5a5-4a85-986f-e7007e9d3efe'}

recv: {'u': '2919cdc3-5570-475a-a647-6b0327e011f7'}

recv: {'u': '2919cdc3-5570-475a-a647-6b0327e011f7'}

recv: {'u': '1afacb8e-bc2f-435f-89ce-46d5b568e1a6'}


============================== 4 passed in 0.05s ===============================

Process finished with exit code 0
```

**Comment by alm0ra** [comment]
@ssmails 
thanks for your raising the issue.

Could you please provide the code snippet that test getting failed instead of printing?

**Comment by alm0ra** [comment]
Dear @ssmails 
I have identified the problem. As outlined in the pull request (PR), we neglected to implement single message commit functionality. Consequently, I refrained from committing anything when you passed this parameter. However, I have now included a new assertion to ensure that we do not consume a message more than once after committing. Once the PR is merged, the issue will be resolved. Should you encounter any further problems, please do not hesitate to inform me, and I will be glad to assist.

**Comment by ssmails** [comment]
Hello @alm0ra , I updated to v0.1.54 , but still seeing the duplicate issue. I ran the test for a smaller range. Please check at your end. Thanks.
@pytest.mark.parametrize("count", range(1, 5))

E       AssertionError: assert 4 == 3
E        +  where 4 = len([{'u': '72d4ee85-fe30-4ece-a5ee-ea23333b9b36'}, {'u': '99d3196e-f5c6-4983-a029-1dc82b8c769c'}, {'u': '561f4207-4659-437b-a217-9d25ee030d40'}, {'u': '561f4207-4659-437b-a217-9d25ee030d40'}])
E        +  and   3 = len({'561f4207-4659-437b-a217-9d25ee030d40', '72d4ee85-fe30-4ece-a5ee-ea23333b9b36', '99d3196e-f5c6-4983-a029-1dc82b8c769c'})
E        +    where {'561f4207-4659-437b-a217-9d25ee030d40', '72d4ee85-fe30-4ece-a5ee-ea23333b9b36', '99d3196e-f5c6-4983-a029-1dc82b8c769c'} = set(['72d4ee85-fe30-4ece-a5ee-ea23333b9b36', '99d3196e-f5c6-4983-a029-1dc82b8c769c', '561f4207-4659-437b-a217-9d25ee030d40', '561f4207-4659-437b-a217-9d25ee030d40'])

**Comment by ssmails** [comment]
Thanks @alm0ra , will check.
