### ISSUE TITLE
`FakeAIOKafkaProducer` need `stop` function

### ISSUE THREAD

**Issue by setmao** [alm0ra/mockafka-py#85]
When I use mockafka-py to write tests, I encountered the following error:
`AttributeError: 'FakeAIOKafkaProducer' object has no attribute 'stop'.`

Here is my code(I referred to this [document](https://aiokafka.readthedocs.io/en/stable/#aiokafkaproducer).): 
```Python
from aiokafka import AIOKafkaProducer
import asyncio

async def send_one():
    producer = AIOKafkaProducer(
        bootstrap_servers='localhost:9092')
    # Get cluster layout and initial topic/partition leadership information
    await producer.start()
    try:
        # Produce message
        await producer.send_and_wait("my_topic", b"Super message")
    finally:
        # Wait for all pending messages to be delivered or expire.
        await producer.stop()
```
I think `FakeAIOKafkaProducer` should have a `stop` function if I want to use mockafka to write a test for aiokafka.

**Comment by alm0ra** [comment]
fixed in[v0.1.56]( https://github.com/alm0ra/mockafka-py/releases/tag/v0.1.56)
