### ISSUE TITLE
Missing 0.1.56 pypi release

### ISSUE THREAD

**Issue by cheungnj** [alm0ra/mockafka-py#95]
**Describe the bug**
There is no 0.1.56 release on pypi but there is a 0.1.56 tag on github.

**Expected behavior**
I should see a 0.1.56 release on pypi.

**Screenshots**

**Desktop (please complete the following information):**
 - python version
 - redis-py version
 - full requirements.txt?

**Additional context**
I can work around this by specifying the github repo and tag in my dependencies.

I couldn't find a way to remove the `bug` label but I think this is more of an operational thing than a bug.

**Comment by alm0ra** [comment]
thanks for notify me ,
fixed

https://github.com/alm0ra/mockafka-py/releases/tag/v0.1.57
https://pypi.org/project/mockafka-py/0.1.57/
